version: 2
updates:
  - package-ecosystem: pub
    directory: "/" 
    schedule:
      interval: "monthly"
      time: "06:30"
      timezone: "Europe/Warsaw"
    target-branch: main
    open-pull-requests-limit: 1
